[tool.poetry]
name = "rag"
version = "0.1.0"
description = ""
authors = ["imyesung <limyesung@protonmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
setuptools = "^72.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
